-- SELECT_{T1,T2}(T)
SELECT T1,T2
FROM T;

-- SELECT_{V3,V1}(V)
SELECT V3,V1
FROM V;

-- p <- SELECT_{T1,T2}(T) - SELECT_{V3,V1}(V)
SELECT T1,T2
FROM T
WHERE (T1,T2) NOT IN (SELECT V3,V1
FROM V);

-- SELECT_{T2=17}(p)
SELECT *
FROM (SELECT T1,T2
FROM T
WHERE (T1,T2) NOT IN (SELECT V3,V1
FROM V)) P
WHERE T2 = 17;